name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags:
      - "^v.*"

jobs:
  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-ci.yml@main
    secrets: inherit
